version: '3'
services: 
  lb:
    image: dockercloud/haproxy
    ports:
      - 3030:80
    links: 
      - hello
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
  hello:
    image: hello-node:v3
#    ports:
#      - 3030:3000